### ISSUE TITLE
scipy dependency pin

### ISSUE THREAD

**Issue by Kirill888** [WFP-VAM/seasmon_xr#26]
is this still relevant?

https://github.com/WFP-VAM/seasmon_xr/blob/97fcfff016e880b8b6fc755a1f137d14d5bb177a/requirements.txt#L5

it's getting rather old, harder to install

**Comment by valpesendorfer** [comment]
There was a dependency issue with `numba-scipy`, which looks to be not the case anymore. So we can probably remove the pin and see if anything pops up
